more esm and vite test coverage (#54)
fixes error:

```
Error: Failed to load .../path/evals/some.eval.ts as 
    CJS (Cannot find module '.../path/scorers' imported from .../path/evals/some.eval.ts) or 
    ESM (Unexpected status of a module that is imported again after being required. Status = 0                                                                                 
    This is caused by either a bug in Node.js or incorrect usage of Node.js internals.    
    Please open an issue with this stack trace at https://github.com/nodejs/node/issues   ).                                                                                        
        at loadFiles (.../bt/eval-runners/0.2.0/eval-runner.ts:1050:17)     
        at main (.../bt/eval-runners/0.2.0/eval-runner.ts:1968:19)      
    error: eval runner exited with status exit status: 1
If this seems like a bug, file an issue at https://github.com/braintrustdata/bt/issues/new and include `bt --version`, `bt status --json`, and the command you ran.
```

root cause is that our runner tries to use require(). vite-node has
hooks that are only used if we use import() instead of require. started
with the tests to repro and then patched the runner
[here](https://github.com/braintrustdata/bt/pull/54/commits/3686bbe2ae42765d8a0af0541b12e6d6c45f7101).